### ISSUE TITLE
GUI is too large

### ISSUE THREAD

**Issue by axredneck** [flathub/org.shadered.SHADERed#7]
![Screenshot_20200904_143455](https://user-images.githubusercontent.com/20617900/92235421-52490180-eebc-11ea-8cd8-92755e55e8b8.png)
Arch Linux, KDE.

**Comment by Calinou** [comment]
@axredneck Can you reproduce this with a non-Flatpak version of SHADERed? This repository should only be used to report issues specific to the Flatpak version.

**Comment by dfranx** [comment]
@axredneck It probably has to do with calculating DPI.. Uncheck "DPI aware" checkbox in `Options` -> `General` and set the UI scale manually.

**Comment by axredneck** [comment]
Yes, non-Flatpak version (from AUR) has the same issue. Closing.

**Comment by aunetx** [comment]
Just for information, it looks like the default font size (18 pixels) is way too big, most programs seem to set it to 14 pixels IIRC
